### ISSUE TITLE
Beiwe GPS data

### ISSUE THREAD

**Issue by HagenFritz** [intelligent-environments-lab/utx000#34]
# How is the GPS data recorded?
The GPS data has large gaps in it which makes me think that perhaps only large changes are recorded which helps save on storage space. 

This could be why in my initial analysis using the GPS data, I was finding wildly different distances from the participant's home to their coordinates. Perhaps I should be looking at only coordinates where significant time was spent. Then from there, I can compare those locations to their home's location. 

## Tasks
- [x] Look at raw GPS data from the Beiwe server for multiple participants to confirm these gaps
- [x] Contact Cameron/Anibal about how the GPS data are recorded

## Extension
We need to get an estimate as to what constitutes a large enough change in distance to register in the GPS data. 
- [x] Determine distances between subsequent Lat/Long points

**Comment by HagenFritz** [comment]
Looked at GPS data and noticed the gaps although they aren't as large as I initially suspected. Still, I am emailed Cameron and Anibal to see how often GPS data are recorded.

**Comment by HagenFritz** [comment]
Cameron replied and said that there IS some threshold and if you don't move far enough, then the GPS coordinates do not change. The example in the documentation says **500 meters**, however this value needs to be tested.

**Comment by HagenFritz** [comment]
Looks like there are plenty of distances between points that are less than 50 meters. The next step would be to see if the timestamps are consistent between smaller distances (meaning that the GPS just logs at a certain rate unless there is a big gap in distance).

**Comment by HagenFritz** [comment]
From my analysis, I cannot seem to find any distance that causes Beiwe to record the GPS coordiantes.
