### ISSUE TITLE
Initial Inspection: Mood and IEQ

### ISSUE THREAD

**Issue by HagenFritz** [intelligent-environments-lab/utx000#89]
Idea is to use the period participants are at home prior to submitted their EMA (while still at home) to see if the IEQ parameters _appreciably_ affect their mood. 

## Task List
- [x] Get periods when participants are home according to GPS data (from Peter)
- [x] Determine summarizing metrics to use for the IEQ parameters
- [x] Compare the effects that IEQ metrics have on participants' moods considering:
  - [x] length of time at home
  - [x] distinct periods of time that participants were home before submitting i.e. thirty minutes, one hour, etc.
  - [x] aggregate and participant levels

**Comment by HagenFritz** [comment]
Data or periods when participants were home have been determined by Peter but only for a _single_ location despite participants moving mid-study. Emailed him about providing data from both locations on 08/18.
