### ISSUE TITLE
UTx000: Predicting Mood from Activity and Previously-Reported Mood

### ISSUE THREAD

**Issue by HagenFritz** [intelligent-environments-lab/utx000#91]
The next step in the process of improving the prediction of evening mood scores is to incorporate some activity metric(s) from Fitbit.

## Tasks
- [x] Need to update functions to handle more features
- [x] Consider ways to binarize activity (10K steps, number of active minutes, distance traveled, etc.)
- [x] Considerations for the amount of time the Fitbit has been worn
- [x] Multi-class vs binary prediction

**Comment by HagenFritz** [comment]
Cannot use number of active minutes to quantify activity level because these values are measured over the entire day but the EMA can be submitted as early as 19:00.
